---
name: "Pages"

on:
  push:
    # Should only run on "main" since we dont want any "dev" changes in our docs before release
    branches: ["main"]

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    permissions:
      issues: write
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
      - run: "pip install mkdocs-material mkdocs-awesome-pages-plugin"
      - run: "mkdocs gh-deploy --force"
